<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Blurhash.Core" Version="4.2.1" />
        <PackageReference Include="SixLabors.ImageSharp" Version="4.0.0" />
    </ItemGroup>
   
    <PropertyGroup>
        <!-- Keep in Sync with the TFM of SixLabors.ImageSharp -->
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <nullable>enable</nullable>
    </PropertyGroup>
    
    <PropertyGroup>
        <PackageId>Blurhash.ImageSharp</PackageId>
        <Authors>Markus Palcer</Authors>
        <Description>BlurHash is a compact representation of a placeholder for an image.</Description>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <Copyright>Copyright 2019 Markus Palcer</Copyright>
        <PackageTags>blurhash image preview compression encoding</PackageTags>
        <PackageProjectUrl>https://github.com/MarkusPalcer/BlurHash.ImageSharp</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <Target Name="SetPackageVersion" BeforeTargets="GenerateNuspec;GetPackageVersion;_GetProjectReferenceVersions;GetAssemblyVersion;BeforeCompile">
        <PropertyGroup>
            <PackageVersion>@(PackageReference->WithMetadataValue('Identity', 'SixLabors.ImageSharp')->Metadata('Version'))</PackageVersion>
            <Version>$(PackageVersion)</Version>
        </PropertyGroup>
    </Target>
</Project>
